name: dj
description: Auto-Generate Dart and Flutter Code while retaining manual user updates to generated code.
version: 0.0.4
homepage: https://www.ark4579.com
repository: https://github.com/ARK4579/dj
issue_tracker: https://github.com/ARK4579/dj/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_annotation: ^4.0.1
  path: ^1.8.0

dev_dependencies:
  json_serializable: ^4.1.0
  build_runner: ^1.12.2
  pedantic: ^1.9.0
  test: ^1.14.4
