name: dj
description: Auto-Genrate Dart & Flutter Code.
version: 0.0.3
homepage: https://www.ark4579.com
repository: https://github.com/ARK4579/dj
issue_tracker: https://github.com/ARK4579/dj/issues

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  json_serializable: ^4.1.0
  path: ^1.8.0

dev_dependencies:
  build_runner: ^1.12.2
  pedantic: ^1.9.0
  test: ^1.14.4
